export const fishHeatmapPoints = [
  {
    id: "istanbul-levrek",
    lat: 41.0082,
    lng: 28.9784,
    species: "Levrek",
    count: 28,
    location: "Istanbul",
    country: "Türkiye",
    waterType: "saltwater",
    lastSeenAt: "2026-04-15",
  },
  {
    id: "new-york-bass",
    lat: 40.7128,
    lng: -74.006,
    species: "Bass",
    count: 41,
    location: "New York",
    country: "USA",
    waterType: "freshwater",
    lastSeenAt: "2026-04-14",
  },
  {
    id: "singapore-clownfish",
    lat: 1.3521,
    lng: 103.8198,
    species: "Clownfish",
    count: 24,
    location: "Singapore",
    country: "Singapore",
    waterType: "saltwater",
    lastSeenAt: "2026-04-13",
  },
  {
    id: "bergen-salmon",
    lat: 60.3913,
    lng: 5.3221,
    species: "Salmon",
    count: 35,
    location: "Bergen",
    country: "Norway",
    waterType: "saltwater",
    lastSeenAt: "2026-04-12",
  },
  {
    id: "munich-trout",
    lat: 48.1351,
    lng: 11.582,
    species: "Trout",
    count: 19,
    location: "Munich",
    country: "Germany",
    waterType: "freshwater",
    lastSeenAt: "2026-04-11",
  },
  {
    id: "izmir-levrek",
    lat: 38.4237,
    lng: 27.1428,
    species: "Levrek",
    count: 22,
    location: "Izmir",
    country: "Türkiye",
    waterType: "saltwater",
    lastSeenAt: "2026-04-10",
  },
  {
    id: "tokyo-bass",
    lat: 35.6762,
    lng: 139.6503,
    species: "Bass",
    count: 17,
    location: "Tokyo",
    country: "Japan",
    waterType: "freshwater",
    lastSeenAt: "2026-04-09",
  },
  {
    id: "sydney-clownfish",
    lat: -33.8688,
    lng: 151.2093,
    species: "Clownfish",
    count: 21,
    location: "Sydney",
    country: "Australia",
    waterType: "saltwater",
    lastSeenAt: "2026-04-08",
  },
] as const;
